services:
- type: web
  name: va-bot
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "./start.sh"
  envVars:
    - key: EMAIL
      sync: false
    - key: APP_PASS
      sync: false
    - key: PAYPAL_EMAIL
      sync: false
    - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
      sync: false
